language: objective-c
osx_image: xcode10.2

script:
  - xcodebuild -project Palladium.xcodeproj -scheme Palladium -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
